<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.31">

  <meta name="author" content="Brad Boehmke">
  <title>ModelOps and Model Experimentation: From Training Runs to Managed Models – ModelOps and Model Experimentation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <meta name="mermaid-theme" content="neutral">
  <script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">ModelOps and Model Experimentation</h1>
  <p class="subtitle">From Training Runs to Managed Models</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Brad Boehmke 
</div>
</div>
</div>

</section>
<section>
<section id="welcome" class="title-slide slide level1 center" data-background="#43464B">
<h1>Welcome</h1>

</section>
<section id="applied-workshops-series" class="slide level2" data-background-image="assets/images/bridge.jpg" data-background-size="cover" data-background-position="center">
<h2>Applied Workshops Series</h2>
<p><strong>Bridging the gap between classroom and industry</strong></p>
<p><br><br><br><br><br><br><br><br> <span style="color: white;">This series shares best practices and industry standards not always covered in coursework — practical skills that can differentiate you early in your career.</span></p>
<aside class="notes">
<p>Frame this as part of the applied workshop series. These workshops focus on practical skills that matter in industry but are often underrepresented in coursework. Today we move from data pipelines into the modeling lifecycle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="todays-agenda" class="slide level2">
<h2>Today’s Agenda</h2>
<ul>
<li>ModelOps overview</li>
<li>Structured experimentation</li>
<li>Experiment tracking with MLflow</li>
<li>Rossmann project walkthrough</li>
<li>Live demo</li>
<li>Wrap-up</li>
</ul>
<p><br></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Today’s Goal</strong></p>
</div>
<div class="callout-content">
<p>Walk out understanding how to move from ad-hoc training runs to structured, trackable model experimentation.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Set expectations: this is practical and hands-on. We’ll start with concepts, ground them in a real project, and then see it live in MLflow. The goal is a mental model you can apply to your own work immediately.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-problem" class="title-slide slide level1 center" data-background="#43464B">
<h1>The Problem</h1>

</section>
<section id="models-in-the-classroom-vs.-production" class="slide level2">
<h2>Models in the Classroom vs.&nbsp;Production</h2>
<div style="text-align: center;">
<p><img data-src="assets/images/classroom-vs-production.png" style="width:90.0%"></p>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Gap</strong></p>
</div>
<div class="callout-content">
<p>Academic projects treat models as artifacts. Industry treats them as <strong>lifecycle assets</strong> that need continuous management.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Start by surfacing the fundamental mindset shift students need to make</li>
<li>Walk through the visual contrast on screen:
<ul>
<li><strong>In school</strong>: Model = one-time deliverable. Train, evaluate, submit. Focus on accuracy. Success = good grade. Lifespan = one assignment</li>
<li><strong>In production</strong>: Model = living asset. Train, deploy, monitor, retrain. Focus on sustained business value. Success = reliable performance over time. Lifespan = months or years</li>
</ul></li>
<li>The skills that get you a good grade (feature engineering, tuning, accuracy) are necessary but not sufficient</li>
<li>Production adds critical questions: Can you reproduce this? Can others use it? Does it still work next month? Can you explain decisions?</li>
<li>This isn’t a criticism of academic work — it’s recognizing that the success criteria are fundamentally different</li>
<li>This gap is what ModelOps addresses — today we start with the foundation: experiment tracking</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="modelops" class="title-slide slide level1 center" data-background="#43464B">
<h1>ModelOps</h1>

</section>
<section id="why-modelops-matters" class="slide level2 smaller">
<h2>Why ModelOps Matters</h2>
<p><strong>Questions that haunt production ML teams:</strong></p>
<ul>
<li>“Which model version is in production?”</li>
<li>“What hyperparameters did we use?”</li>
<li>“Can you reproduce last quarter’s results?”</li>
<li>“Why did performance drop?”</li>
</ul>
<div class="fragment">
<p><br></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Root Problem</strong></p>
</div>
<div class="callout-content">
<p>Most teams focus on training accuracy but neglect <strong>reproducibility, versioning, deployment, and monitoring</strong> — the foundation for production ML systems.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>The solution:</strong> Manage models as <strong>lifecycle assets</strong>, not just training artifacts.</p>
<aside class="notes">
<ul>
<li>Start with the pain — these are real questions that come up in industry constantly</li>
<li>Without systematic practices, the answers are often “I’m not sure” or “let me dig through old notebooks”</li>
<li>In school, the finish line is model accuracy. In industry, that’s the starting line</li>
<li>The problem: teams build models but can’t reproduce them, deploy them confidently, or maintain them over time</li>
<li>This slide hooks students with the problem before introducing ModelOps as the solution</li>
<li>The last line sets up the next slide: “What does it mean to manage models as lifecycle assets?”</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="what-is-modelops" class="slide level2 smaller">
<h2>What Is ModelOps?</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>ModelOps</strong></p>
</div>
<div class="callout-content">
<p>Management of the lifecycle of machine learning models</p>
</div>
</div>
</div>
<p><br></p>
<div class="cell" data-reveal="true" data-fig-width="9" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart RL
    subgraph dt[DataOps]
    direction LR
    end
    subgraph ml[ModelOps]
    direction LR
    m1[Model Experimentation]
    m2[Model Versioning]
    m3[Model Deployment]
    m4[Model Monitoring]
    m1 --&gt; m2 --&gt; m3 --&gt; m4 --&gt; m1
    end
    dt --&gt; ml --&gt; dt
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>ModelOps is the discipline of managing models throughout their entire lifecycle</li>
<li>The lifecycle is a cycle: experimentation → versioning → deployment → monitoring → back to experimentation</li>
<li>Note how this connects to DataOps — reliable models depend on reliable data pipelines</li>
<li>Each stage feeds into the next, and monitoring in production informs future experiments</li>
<li>Most people think “ML” means training a model. That’s only one piece of a much larger system</li>
<li>Today we focus on the first stage: experimentation and tracking</li>
<li>Let’s break down what each stage actually does…</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-four-stages-of-modelops" class="slide level2 smaller">
<h2>The Four Stages of ModelOps</h2>
<ul>
<li class="fragment"><p><strong>Model Experimentation</strong> Track parameters, metrics, and artifacts to enable reproducible, comparable training runs. <em>Foundation for everything else.</em></p></li>
<li class="fragment"><p><strong>Model Versioning</strong> Ensure transparency regarding model lineage — know exactly what data, code, and hyperparameters produced each model version.</p></li>
<li class="fragment"><p><strong>Model Deployment</strong> Bridge the gap between experimentation and real-world application, ensuring models deliver value in production environments.</p></li>
<li class="fragment"><p><strong>Model Monitoring</strong> Continuously track model behavior in production to identify performance degradation and trigger retraining when needed.</p></li>
</ul>
<aside class="notes">
<ul>
<li>Now we go deeper into each stage of the lifecycle</li>
<li><strong>Experimentation</strong>: This is today’s focus. Without tracking, you can’t compare runs, reproduce results, or build systematically</li>
<li><strong>Versioning</strong>: Every model needs a lineage — what data version, what code commit, what hyperparameters. This is how you answer “can you reproduce last quarter’s model?”</li>
<li><strong>Deployment</strong>: Getting a model into production is its own discipline — APIs, containers, scaling, rollback strategies</li>
<li><strong>Monitoring</strong>: Models degrade over time as data distributions shift. Monitoring catches this and signals when retraining is needed</li>
<li>The cycle repeats: monitoring insights feed back into new experiments, improved models get versioned and deployed</li>
<li>These stages build on each other — you can’t version what you haven’t tracked, can’t deploy what you haven’t versioned, can’t monitor effectively without knowing what you deployed</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-these-stages-matter-in-industry" class="slide level2 smaller">
<h2>Why These Stages Matter in Industry</h2>
<ul>
<li class="fragment"><p><strong>Scalability</strong>: Standardizes workflows for deploying and managing multiple models across various environments.</p></li>
<li class="fragment"><p><strong>Reproducibility</strong>: Provides an audit trail of datasets, code, hyperparameters, and model versions throughout the lifecycle.</p></li>
<li class="fragment"><p><strong>Collaboration</strong>: Creates a structured framework that promotes transparency and knowledge sharing across teams.</p></li>
<li class="fragment"><p><strong>Reliability</strong>: Ensures models maintain performance over time, not just at initial deployment.</p></li>
<li class="fragment"><p><strong>Regulatory Compliance</strong>: Delivers the transparency and traceability needed to meet legal and ethical standards.</p></li>
</ul>
<aside class="notes">
<ul>
<li>Now tie it to industry context — why do organizations invest in ModelOps?</li>
<li><strong>Scalability</strong>: Think about managing 10, 50, or 100+ models. Without standardization, it becomes chaos</li>
<li><strong>Reproducibility</strong>: Critical for auditing, debugging, and regulatory requirements. In finance and healthcare, you must be able to recreate any model decision</li>
<li><strong>Collaboration</strong>: Multiple data scientists working together need consistent practices. ModelOps provides that structure</li>
<li><strong>Reliability</strong>: Models degrade over time as data distributions shift. The monitoring stage catches this</li>
<li><strong>Compliance</strong>: Regulated industries (finance, healthcare, insurance) must explain and justify model decisions. Full lifecycle tracking makes this possible</li>
<li>This isn’t overhead — it’s how professional data science works at scale</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modelops-challenges" class="slide level2 smaller">
<h2>ModelOps Challenges</h2>
<p><br></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Reality</strong></p>
</div>
<div class="callout-content">
<p>ModelOps requires investment and discipline. Common challenges include:</p>
</div>
</div>
</div>
<ul>
<li class="fragment"><strong>Integration Complexity</strong>: Interoperability between the myriad tools and systems used throughout the ML lifecycle.</li>
<li class="fragment"><strong>Infrastructure Costs</strong>: The cost of scaling infrastructure to meet these demands can be prohibitive for many organizations.</li>
<li class="fragment"><strong>Team Expertise</strong>: Requires cross-functional skills and expertise in data science, software engineering, and DevOps.</li>
<li class="fragment"><strong>Evolving Standards</strong>: New tools, techniques, and best practices emerge frequently, requiring organizations to adapt continuously.</li>
</ul>
<aside class="notes">
<ul>
<li>Be honest about the challenges — ModelOps isn’t free</li>
<li>Integration: most orgs have existing data pipelines, deployment systems, monitoring tools — making them work together is hard</li>
<li>Infrastructure: running experiment tracking servers, model registries, monitoring systems costs money and maintenance</li>
<li>Team expertise: you need people who understand both the data science and the engineering</li>
<li>Evolving standards: the landscape changes constantly — what’s best practice today might be outdated in a year</li>
<li>But here’s the key: you can start small. Today we focus on experiment tracking — something you can adopt with minimal infrastructure</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="experimentation" class="title-slide slide level1 center" data-background="#43464B">
<h1>Experimentation</h1>

</section>
<section id="how-do-you-track-experiments-today" class="slide level2 smaller">
<h2>How Do You Track Experiments Today?</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Typical workflow:</strong></p>
<ul>
<li>Train a model in a notebook</li>
<li>Tweak some parameters</li>
<li>Rerun the cell</li>
<li>Rename the notebook (<code>model_v2_final_FINAL.ipynb</code>)</li>
<li>Copy-paste results into a spreadsheet</li>
<li>Comment out old code</li>
<li>Try to remember what worked</li>
</ul>
</div><div class="column" style="width:50%;">
<p><img data-src="assets/images/messy-notebook-files.png"></p>
</div></div>
<p><br></p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Sound familiar?</strong></p>
</div>
<div class="callout-content">
<p>Most of us have been here. It works for small projects, but doesn’t scale. In industry, it’s not uncommon to try tens, hundreds, or even <strong>thousands</strong> of experiments!</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Ask students directly: “How do you keep track of your model experiments right now?”</li>
<li>Let a few people answer — you’ll hear things like “I rename notebooks”, “I keep a spreadsheet”, “I just remember”</li>
<li>Show of hands: “Who has a file called something_final_v2 or model_FINAL_REALLY_FINAL?”</li>
<li>Don’t judge — make it relatable. Everyone starts here. This is the natural first approach</li>
<li>But without structure, you lose track of what works, what changed, and how to reproduce results</li>
<li>The goal of this slide is to surface the tactical pain before offering the solution</li>
<li>Transition: let’s talk about what specifically goes wrong with this approach</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-problems" class="slide level2 smaller">
<h2>The Problems</h2>
<div class="columns">
<div class="column" style="width:33%;">
<p><strong>Which run was best?</strong></p>
<p>You trained 15 models. Three weeks later, which one had the best performance?</p>
<p>Where are those hyperparameters?</p>
</div><div class="column" style="width:33%;">
<p><strong>What changed?</strong></p>
<p>You improved RMSE by 12%. Was it the feature engineering? The learning rate? The data split?</p>
<p>You don’t know.</p>
</div><div class="column" style="width:34%;">
<p><strong>Can you reproduce it?</strong></p>
<p>Your manager asks you to rerun last month’s best model.</p>
<p>Can you recreate the exact same result?</p>
</div></div>
<div style="text-align: center;">
<p><img data-src="assets/images/experimentation-problems.png" style="width:100.0%"></p>
</div>
<aside class="notes">
<ul>
<li>Walk through each problem concretely</li>
<li>“Which run was best?” — when you have a dozen notebooks with different experiments, finding the best one becomes archaeology</li>
<li>“What changed?” — without logging, you can’t attribute improvement to a specific change</li>
<li>“Can you reproduce?” — this is the killer. If you can’t reproduce results, you can’t trust them, deploy them, or build on them</li>
<li>These problems compound as teams grow and projects mature</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="good-modeling-structured-experimentation" class="slide level2">
<h2>Good Modeling = Structured Experimentation</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Principle</strong></p>
</div>
<div class="callout-content">
<p>Treat each training run as a <strong>trackable experiment</strong>, not a throwaway cell execution.</p>
</div>
</div>
</div>
<p><br></p>
<p>Every experiment should capture:</p>
<ul>
<li>What you tried (parameters, algorithm, data &amp; features used)</li>
<li>What happened (metrics, performance)</li>
<li>What you produced (model artifacts)</li>
</ul>
<aside class="notes">
<ul>
<li>This is the core mindset shift</li>
<li>A notebook cell execution is ephemeral — an experiment is a permanent record</li>
<li>Structured experimentation doesn’t mean more work — it means the right work</li>
<li>Think of it like a lab notebook in science: you record what you did so others (and future you) can understand and reproduce it</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-to-track" class="slide level2 smaller">
<h2>What to Track</h2>
<div class="cell" data-reveal="true" data-fig-width="12" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["&lt;b&gt;Parameters&lt;/b&gt;&lt;br/&gt;Learning rate&lt;br/&gt;Max depth&lt;br/&gt;Algorithm"] --&gt; E[Experiment Run]
    B["&lt;b&gt;Data &amp; Features&lt;/b&gt;&lt;br/&gt;Dataset version&lt;br/&gt;Feature engineering&lt;br/&gt;Train/test splits"] --&gt; E
    C["&lt;b&gt;Metrics&lt;/b&gt;&lt;br/&gt;RMSE, MAE, R²&lt;br/&gt;Per-fold CV scores"] --&gt; E
    D["&lt;b&gt;Artifacts&lt;/b&gt;&lt;br/&gt;Trained model&lt;br/&gt;Predictions&lt;br/&gt;Feature importance"] --&gt; E
    E --&gt; F["&lt;b&gt;Tracked Record&lt;/b&gt;&lt;br/&gt;Reproducible&lt;br/&gt;Comparable&lt;br/&gt;Shareable"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Four categories of things to track for every experiment run</li>
<li><strong>Parameters</strong>: hyperparameters that control the algorithm — learning rate, max depth, regularization</li>
<li><strong>Data &amp; Features</strong>: what data you used — dataset version, feature engineering steps, train/test/validation splits. Critical for reproducibility</li>
<li><strong>Metrics</strong>: the results — RMSE, MAE, accuracy, per-fold cross-validation scores</li>
<li><strong>Artifacts</strong>: the outputs — the trained model file, predictions CSV, feature importance plots</li>
<li>Together, these create a complete record that can be compared, reproduced, and shared</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-structure-matters" class="slide level2">
<h2>Why Structure Matters</h2>
<div style="text-align: center;">
<p><img data-src="assets/images/structure-matters.png" style="width:90.0%"></p>
</div>
<aside class="notes">
<ul>
<li>Walk through the three benefits shown in the visual:</li>
<li><strong>Compare</strong>: when you have 100 hyperparameter trials logged, you can sort by metric and instantly find the best configuration. Side-by-side comparison across runs helps identify what works and what doesn’t</li>
<li><strong>Reproduce</strong>: if a model in production degrades, you can go back to the exact experiment that produced it and understand what’s different. Essential for debugging and auditing</li>
<li><strong>Explain</strong>: in industry, you need to justify model choices to non-technical stakeholders. Tracked experiments give you evidence and demonstrate rigor in your process</li>
<li>This isn’t overhead — it’s how professional data science works</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="mlflow" class="title-slide slide level1 center" data-background="#43464B">
<h1>MLflow</h1>

</section>
<section id="what-is-mlflow" class="slide level2 smaller">
<h2>What Is MLflow?</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>MLflow</strong></p>
</div>
<div class="callout-content">
<p>An open-source platform for managing the end-to-end ML lifecycle — experiment tracking, model versioning, and deployment.</p>
</div>
</div>
</div>
<p><strong>Why MLflow?</strong></p>
<ul>
<li>Open source and free</li>
<li>Integrated into many platforms (Databricks, AWS SageMaker, Azure ML)</li>
<li>Works with any ML library (scikit-learn, XGBoost, LightGBM, PyTorch)</li>
<li>Simple Python API</li>
<li>Built-in UI for comparing experiments</li>
<li>Model registry for versioning</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Other Options</strong></p>
</div>
<div class="callout-content">
<p>MLflow is one of the most widely adopted experiment tracking tools, but alternatives include Weights &amp; Biases, Neptune.ai, Comet.ml, and DVC.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>MLflow is the tool we’ll use for experiment tracking today</li>
<li>It’s not the only option — Weights &amp; Biases, Comet.ml, Neptune.ai, and DVC are alternatives</li>
<li>We use MLflow because it’s open source, widely adopted, and integrates with virtually any ML framework</li>
<li>It has four main components: tracking, projects, models, and registry. Today we focus on tracking</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-mental-model" class="slide level2 smaller">
<h2>The Mental Model</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Key Concept</strong></p>
</div>
<div class="callout-content">
<p>A <strong>run</strong> = one experiment attempt. An <strong>experiment</strong> = a collection of related runs.</p>
</div>
</div>
</div>
<p><br></p>
<div class="cell" data-reveal="true" data-fig-width="10" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["&lt;b&gt;Experiment&lt;/b&gt;&lt;br/&gt;rossmann-forecasting"] --&gt; B["Run 1&lt;br/&gt;Naive Baseline"]
    A --&gt; C["Run 2&lt;br/&gt;LightGBM Default"]
    A --&gt; D["Run 3&lt;br/&gt;XGBoost Tuned"]
    A --&gt; E["Run 4&lt;br/&gt;Ensemble"]

    B --&gt; F["params + metrics + artifacts"]
    C --&gt; G["params + metrics + artifacts"]
    D --&gt; H["params + metrics + artifacts"]
    E --&gt; I["params + metrics + artifacts"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>An <strong>experiment</strong> groups related runs together under one name (e.g., “rossmann-forecasting”)</li>
<li>A <strong>run</strong> is a single training attempt — one set of hyperparameters, one model, one set of results</li>
<li>Each run captures parameters, metrics, and artifacts automatically</li>
<li>You can have hundreds of runs in one experiment — MLflow makes them searchable, sortable, and comparable</li>
<li>This is the mental model to carry through the rest of the workshop</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-tracking-works" class="slide level2 smaller">
<h2>How Tracking Works</h2>
<p>Every model run follows this pattern:</p>
<p><br></p>
<div class="cell" data-reveal="true" data-fig-width="10" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A[Start Run] --&gt; B[Log Parameters]
    B --&gt; C[Train Model]
    C --&gt; D[Log Metrics]
    D --&gt; E[Save Artifacts]
    E --&gt; F[Log Metadata]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p><br></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> mlflow.start_run(run_name<span class="op">=</span><span class="st">"lightgbm_baseline"</span>):</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"learning_rate"</span>, <span class="fl">0.01</span>)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"max_depth"</span>, <span class="dv">6</span>)</span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="co"># Train &amp; evaluate model</span></span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a>    model.fit(X_train, y_train)</span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb1-8"><a aria-hidden="true" tabindex="-1"></a>    mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb1-9"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a aria-hidden="true" tabindex="-1"></a>    mlflow.log_metric(<span class="st">"mse"</span>, mse)</span>
<span id="cb1-11"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a aria-hidden="true" tabindex="-1"></a>    mlflow.sklearn.log_model(model, <span class="st">"model"</span>)</span>
<span id="cb1-13"><a aria-hidden="true" tabindex="-1"></a>    mlflow.set_tag(<span class="st">"experiment_type"</span>, <span class="st">"baseline"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<aside class="notes">
<ul>
<li>Walk through the code pattern step by step</li>
<li><code>start_run</code> creates a tracked context — everything inside gets logged</li>
<li><code>log_param</code> records hyperparameters — these define the experiment</li>
<li>After training, <code>log_metric</code> records results</li>
<li><code>log_model</code> saves the actual trained model as an artifact</li>
<li><code>set_tag</code> adds searchable metadata for filtering in the UI</li>
<li>This is the core pattern you’ll see in every MLflow-integrated project</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-mlflow-captures" class="slide level2 smaller">
<h2>What MLflow Captures</h2>
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 42%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>What’s Logged</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Run Name</strong></td>
<td>Descriptive identifier</td>
<td><code>lightgbm_tuning_trial_42</code></td>
</tr>
<tr class="even">
<td><strong>Parameters</strong></td>
<td>Hyperparameters &amp; config</td>
<td><code>learning_rate=0.01</code>, <code>max_depth=6</code></td>
</tr>
<tr class="odd">
<td><strong>Metrics</strong></td>
<td>Performance scores</td>
<td><code>cv_rmspe_mean=0.098</code>, per-fold RMSPE</td>
</tr>
<tr class="even">
<td><strong>Artifacts</strong></td>
<td>Files (models, data, plots)</td>
<td>Trained model, predictions CSV</td>
</tr>
<tr class="odd">
<td><strong>Tags</strong></td>
<td>Searchable metadata</td>
<td><code>experiment_type="tuning"</code></td>
</tr>
<tr class="even">
<td><strong>System Info</strong></td>
<td>Environment details</td>
<td>Python version, library versions</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>MLflow automatically captures system information (Python version, library versions) so you know the exact environment</li>
<li>Run names should be descriptive — <code>lightgbm_lr0.01_depth6</code> is better than <code>run_42</code></li>
<li>Tags are powerful for filtering — you can search for all “baseline” runs or all “tuning” runs in the UI</li>
<li>Artifacts can be anything: models, CSVs, plots, configuration files</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-mlflow-ui" class="slide level2">
<h2>The MLflow UI</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="assets/images/mlflow-ui-runs.png"></p>
</div><div class="column" style="width:50%;">
<p><strong>The UI lets you:</strong></p>
<ul>
<li>Compare runs side-by-side</li>
<li>Sort and filter by any metric</li>
<li>View logged parameters and artifacts</li>
<li>Download models for further use</li>
<li>Trace model lineage</li>
</ul>
</div></div>
<aside class="notes">
<ul>
<li>After running experiments, launch the UI with <code>mlflow ui</code> in the terminal</li>
<li>Opens at http://localhost:5000 by default</li>
<li>Walk through the screenshot: point out the experiment list, run table, columns for metrics/parameters</li>
<li>Show that you can select multiple runs and compare them</li>
<li>The UI is where the value of tracking becomes tangible — instead of digging through notebooks, everything is searchable and sortable</li>
<li>You can filter runs by metrics (e.g., show me all runs with RMSPE &lt; 0.10)</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="rossmann-project" class="title-slide slide level1 center" data-background="#43464B">
<h1>Rossmann Project</h1>

</section>
<section id="rossmann-store-sales-forecasting" class="slide level2 smaller">
<h2>Rossmann Store Sales Forecasting</h2>
<p><strong>The project:</strong></p>
<p>Forecast daily sales for <strong>3,000+ retail stores</strong> across a full region</p>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Why this example?</strong></p>
<ul>
<li>Real-world Kaggle competition</li>
<li>Multiple modeling approaches</li>
<li>Natural progression from simple to complex</li>
<li>Full MLflow integration</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>MLflow tracks everything:</strong></p>
<ul>
<li>Baseline models</li>
<li>Hyperparameter tuning trials</li>
<li>Final ensemble model</li>
<li>Model registry</li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><a href="https://github.com/bradleyboehmke/rossmann-forecasting" class="uri">https://github.com/bradleyboehmke/rossmann-forecasting</a></p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>The Rossmann project is our running example throughout this workshop series</li>
<li>In the DataOps workshop, we looked at data pipelines. Now we look at the modeling side</li>
<li>This project uses MLflow to track every experiment from naive baselines through advanced ensembles</li>
<li>It demonstrates a realistic experimentation workflow — the kind you’d use in industry</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-experimentation-workflow" class="slide level2 smaller scrollable">
<h2>The Experimentation Workflow</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-reveal="true" data-fig-width="9" data-fig-height="5.5" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    subgraph EXP["Experimentation Workflow"]
        A["&lt;b&gt;NB 03:&lt;/b&gt; Baseline Models&lt;br/&gt;Naive: RMSPE 0.47&lt;br/&gt;LightGBM: RMSPE 0.14"]
        B["&lt;b&gt;NB 04:&lt;/b&gt; Advanced Models&lt;br/&gt;Tuned LightGBM, XGBoost, CatBoost&lt;br/&gt;Initial ensemble"]
        C["&lt;b&gt;NB 04b:&lt;/b&gt; Hyperparameter Tuning&lt;br/&gt;50 Optuna trials per model&lt;br/&gt;XGBoost: 0.122, LightGBM: 0.127, CatBoost: 0.130"]
        D["&lt;b&gt;NB 05:&lt;/b&gt; Final Evaluation&lt;br/&gt;Weighted ensemble (60% XGBoost, 30% LightGBM, 10% CatBoost)&lt;br/&gt;Register in MLflow Model Registry"]

        A --&gt; B
        B --&gt; C
        C --&gt; D
    end

    EXP --&gt; E["&lt;b&gt;MLflow Tracking&lt;/b&gt;&lt;br/&gt;All runs logged in real-time&lt;br/&gt;Compare across all experiments"]

    style A fill:#e1f5ff
    style B fill:#e1f5ff
    style C fill:#e1f5ff
    style D fill:#e1f5ff
    style E fill:#fff4e6
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><img data-src="assets/images/rossmann-notebooks.png"></p>
</div></div>
<aside class="notes">
<ul>
<li>Walk through the actual 4-notebook experimentation workflow from the Rossmann project</li>
<li><strong>Notebook 03 — Baselines</strong>: Starts with naive baseline (last week’s sales, RMSPE 0.47) and simple LightGBM with default params (RMSPE 0.14). This establishes the performance floor</li>
<li><strong>Notebook 04 — Advanced Models</strong>: Trains tuned LightGBM, XGBoost, and CatBoost with manually specified hyperparameters. Creates initial weighted ensemble</li>
<li><strong>Notebook 04b — Hyperparameter Tuning</strong>: Uses Optuna for automated hyperparameter search. 50 trials per model. All tracked in MLflow. Best results: XGBoost 0.122, LightGBM 0.127, CatBoost 0.130</li>
<li><strong>Notebook 05 — Final Evaluation</strong>: Creates final weighted ensemble (60% XGBoost, 30% LightGBM, 10% CatBoost), evaluates on holdout set, and registers in MLflow Model Registry</li>
<li>During the demo, we’ll run these notebooks and watch the experiments appear in MLflow in real-time</li>
<li>Each phase builds systematically — baselines → advanced models → automated tuning → final evaluation</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="demo" class="title-slide slide level1 center" data-background="#43464B">
<h1>Demo</h1>
<aside class="notes">
<ul>
<li>This is where you’ll do the live demonstration</li>
<li>Demo plan:
<ol type="1">
<li>Navigate to the rossmann-forecasting project directory: <code>cd ~/Desktop/Projects/rossmann-forecasting</code></li>
<li>Launch MLflow UI: <code>mlflow ui</code></li>
<li>Open browser to http://localhost:5000</li>
<li>Open Jupyter Lab: <code>jupyter lab</code> and navigate to notebooks/</li>
<li>Run notebook 03 (baselines) and show how experiments appear in MLflow</li>
<li>Optionally run notebook 04b (hyperparameter tuning) to show Optuna trials being logged</li>
<li>In MLflow UI, demonstrate:
<ul>
<li>Viewing all runs in the experiment</li>
<li>Sorting by metrics (RMSPE)</li>
<li>Comparing multiple runs side-by-side</li>
<li>Viewing parameters and artifacts</li>
<li>Filtering by tags</li>
</ul></li>
</ol></li>
<li>Keep it interactive — ask students what they notice as experiments are logged</li>
<li>Emphasize: this is happening in real-time as code executes</li>
<li>The value becomes tangible when they see dozens/hundreds of experiments organized and searchable</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>

<section>
<section id="wrap-up" class="title-slide slide level1 center" data-background="#43464B">
<h1>Wrap-Up</h1>

</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<p><br></p>
<ul>
<li><p><strong>ModelOps = lifecycle management</strong>: Training is just the beginning</p></li>
<li><p><strong>Experiments need structure</strong>: Track parameters, metrics, and artifacts for every run</p></li>
<li><p><strong>MLflow enables tracking</strong>: Open source, simple API, powerful UI for comparison</p></li>
</ul>
<aside class="notes">
<ul>
<li>Reinforce the three core takeaways</li>
<li>ModelOps is about the full lifecycle, not just training accuracy</li>
<li>Structured experimentation is what separates ad-hoc notebook work from professional data science</li>
<li>MLflow is a practical tool that makes this achievable without heavy infrastructure</li>
<li>These concepts apply regardless of the tool — the principles matter more than any specific platform</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="study-the-rossmann-repository" class="slide level2 smaller">
<h2>Study the Rossmann Repository</h2>
<p><strong>Explore how experimentation fits into a production-grade ML project:</strong></p>
<p><br></p>
<div class="columns">
<div class="column">
<p><strong>What to look for:</strong></p>
<ul>
<li>How experiments are organized</li>
<li>What gets logged for each run</li>
<li>How baselines establish benchmarks</li>
<li>How tuning narrows the search</li>
<li>How the final model is registered</li>
</ul>
</div><div class="column">
<p><strong>Key files:</strong></p>
<ul>
<li><code>src/utils/mlflow_utils.py</code></li>
<li><code>src/models/train_final.py</code></li>
<li><code>src/models/model_registry.py</code></li>
<li><code>config/params.yaml</code></li>
<li><code>docs/modelops/tracking.md</code></li>
</ul>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><a href="https://bradleyboehmke.github.io/rossmann-forecasting/modelops/overview/" class="uri">https://bradleyboehmke.github.io/rossmann-forecasting/modelops/overview/</a></p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Encourage students to spend real time with this repo</li>
<li>Point out the key files: mlflow_utils.py has the tracking utilities, train_final.py shows the production training pattern, model_registry.py handles model versioning</li>
<li>The tracking documentation in docs/modelops/tracking.md walks through the full experimentation workflow</li>
<li>This is their reference implementation for how to do experiment tracking in practice</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="now-start-practicing" class="slide level2 smaller">
<h2>Now Start Practicing</h2>
<p><strong>Apply these concepts to your own projects:</strong></p>
<ul>
<li>Add MLflow tracking to an existing project</li>
<li>Start with simple <code>log_param</code> and <code>log_metric</code> calls</li>
<li>Use the UI to compare your experiments</li>
</ul>
<p><br></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Getting Started</strong></p>
</div>
<div class="callout-content">
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install mlflow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mlflow</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>mlflow.set_experiment(<span class="st">"my-project"</span>)</span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> mlflow.start_run(run_name<span class="op">=</span><span class="st">"first_experiment"</span>):</span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"model_type"</span>, <span class="st">"random_forest"</span>)</span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>    mlflow.log_metric(<span class="st">"rmse"</span>, <span class="fl">0.45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="ex">mlflow</span> ui</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Give them a concrete starting point — three commands to go from zero to tracked experiments</li>
<li>Emphasize: start simple. You don’t need to track everything on day one. Even logging model type and one metric is a huge improvement over nothing</li>
<li>The habit matters more than the completeness. Once you start tracking, you’ll naturally want to track more</li>
<li>Point them to the MLflow documentation for deeper exploration</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="thank-you" class="slide level2" data-background="#43464B">
<h2>Thank You!</h2>
<p><strong>Questions?</strong></p>
<p><br><br></p>
<p><strong>Resources:</strong></p>
<ul>
<li><a href="https://github.com/bradleyboehmke/rossmann-forecasting">Rossmann Forecasting Project</a></li>
<li><a href="https://mlflow.org/docs/latest/index.html">MLflow Documentation</a></li>
<li><a href="https://mlflow.org/docs/latest/getting-started/index.html">MLflow Quickstart</a></li>
</ul>
<aside class="notes">
<p>Open for questions. Encourage students to reach out after the workshop.</p>
<p>Final encouragement: “Start small. Add MLflow to one project this week. Track one experiment. See how it feels. The hardest part is starting — once you see the value, you won’t go back to untracked experiments.”</p>
<p>Remind them: the Rossmann repo is their reference implementation. They can study it, fork it, and apply the same patterns to their own work.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://bradleyboehmke.github.io/model-experimentation">https://bradleyboehmke.github.io/model-experimentation</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>